### ISSUE TITLE
Unclear what to create

### ISSUE THREAD

**Issue by robcrock** [datavis-tech/community#1]
When I click "Create" I am presented with a list of options. The options are visualization or dataset, in that order, which, to me, implies that one comes before the other. I know a data visualization can't be created before a dataset, so a change of the order could help. However, since they are so intimately linked it might be better to create one flow for "Create a visualization" that makes the addition of a dataset part of the flow.

**Comment by curran** [comment]
This is a great point. The mental model of datasets being published independently of visualizations is something we need to clarify. Agreed that the flow now is far from ideal UX-wise.

Perhaps the best solution short-term would be to have a brief intro video for how to use the platform.

**Comment by curran** [comment]
We rearranged the menu to represent the ordering that things need to be created in.

![image](https://user-images.githubusercontent.com/68416/36214078-78edf1ba-11ce-11e8-9ca1-2e3b4e9861cb.png)

I think I'll close this issue, but we're definitely thinking about ways to make the flow more clear. Thanks for the feedback!
