### ISSUE TITLE
Download visualization

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/community#13]
How do I download visualization?

**Comment by curran** [comment]
It's a great idea and in our TODO list!

We're planning on having visualization download as a .zip file of HTML plus all files, so you can run the visualization in other contexts, outside the platform.

Is this the sort of download you have in mind? Or were you thinking of downloading the image?

**Comment by curran** [comment]
We added this feature today woohoo!

![image](https://user-images.githubusercontent.com/68416/36425309-6d2b2936-166c-11e8-8240-6f2554a029ec.png)

Exports to vanilla HTML (http://bl.ocks.org -compatible!).
