### ISSUE TITLE
Placeholder text under Description

### ISSUE THREAD

**Issue by robcrock** [datavis-tech/community#2]
When I go to create a new visualization I am prompted to enter a title and description. In the description field, I noticed placeholder text that lets me know this text is optional. It would be better to state the optional nature of description outside the placeholder text so users don't need to read into the placeholder text to see that it's optional. That way you can get rid of all placeholder text.

**Comment by curran** [comment]
That's a great idea! Will plan on making this change.

**Comment by curran** [comment]
We changed the UI based on your suggestions here. Check it out!

Create page:
![image](https://user-images.githubusercontent.com/68416/36351663-535eb5e4-14d3-11e8-9656-963b7c52474d.png)

Edit page:
![image](https://user-images.githubusercontent.com/68416/36351666-63ca6446-14d3-11e8-96fc-30f3d12d7602.png)

Closing.
