### ISSUE TITLE
Massive empty description block

### ISSUE THREAD

**Issue by robcrock** [datavis-tech/community#3]
I created a new visualization without a description, yet when I look at the starter the description is massive and empty. This is offputting. If someone decided not to describe their visualization, then the description should be downplayed significantly not emphasized.

**Comment by curran** [comment]
Interesting. Is this on the edit page (e.g. `https://datavis.tech/edit/3f1db9ece0994057a3bce7c1ab7f056c`), or the view page (e.g. `https://datavis.tech/vis/3f1db9ece0994057a3bce7c1ab7f056c`)?

I believe on the view page, it should shrink down to nothing, but in the edit page it will be a large empty box. Maybe what we need there is some placeholder text for visualization authors, like "Enter your description here (Markdown supported)".

**Comment by curran** [comment]
@robcrock We changed the UI based on your suggestions here. Check it out!

![image](https://user-images.githubusercontent.com/68416/36351663-535eb5e4-14d3-11e8-9656-963b7c52474d.png)

![image](https://user-images.githubusercontent.com/68416/36351666-63ca6446-14d3-11e8-96fc-30f3d12d7602.png)

Closing.
