### ISSUE TITLE
Where is my dataset

### ISSUE THREAD

**Issue by robcrock** [datavis-tech/community#4]
When I click the radio button to look at my dataset I am presented with the index.html, not a dataset. This is confusing as I see the same index.html below my visualization when that radio button is selected. Maybe users could be presented with a drop zone or "upload new dataset" prompt when they toggle to look at their dataset before they have uploaded a dataset?

**Comment by curran** [comment]
Thanks for this feedback!

I think this is the radio button you mean:

![image](https://user-images.githubusercontent.com/68416/35856359-cb983282-0b5b-11e8-95a9-108827599d76.png)

When you switch it to "visualization", then this document becomes a visualization document and is no longer a visualization.

This is something left over, actually, from a previous version, where there was just a "Create" button, then from there you could set its type to visualization or dataset.

Given that now (in a recent update) you can click "Create visualization" or "Create dataset", I don't think those radio buttons make sense anymore and we should remove them.

Will follow up here once we remove them! Thanks again for the feedback.

**Comment by curran** [comment]
Hey @robcrock We fixed this. Woohoo! Thanks for the suggestion.
