### ISSUE TITLE
Line numbers in code editor

### ISSUE THREAD

**Issue by robcrock** [datavis-tech/community#9]
If line numbers could be added to the code editor then I can tell my collaborator what line I'm working instead of asking them to hunt for the same line of text.

**Comment by curran** [comment]
Great idea! It may clutter the editor a bit, but not too badly. Would be well worth it as an initial solution to finding cod while collaborating. Related to #6 .

**Comment by curran** [comment]
Feature added 🎉

There are now line numbers in the editor.

![image](https://user-images.githubusercontent.com/68416/36222733-4e2df834-11e8-11e8-98e0-528e41059471.png)

Thanks @robcrock for the suggestion!
